export const PROPERTY_TYPE_LABELS: Record<string, string> = {
  condo: "คอนโดมิเนียม",
  house: "บ้านเดี่ยว",
  townhouse: "ทาวน์เฮาส์",
  land: "ที่ดิน",
  apartment: "อพาร์ทเมนต์",
  commercial: "อาคารพาณิชย์",
};

export const LISTING_TYPE_LABELS: Record<string, string> = {
  sale: "ขาย",
  rent: "เช่า",
};

export const PROPERTY_TYPE_CATEGORIES: Record<string, string[]> = {
  condo: [
    "general",
    "security",
    "recreation",
    "convenience",
    "parking",
    "wellness",
    "outdoor",
  ],
  apartment: [
    "general",
    "security",
    "recreation",
    "convenience",
    "parking",
    "wellness",
    "outdoor",
  ],
  house: ["general", "security", "parking", "outdoor", "utilities"],
  townhouse: ["general", "security", "parking", "outdoor", "utilities"],
  land: ["utilities"],
  commercial: ["security", "convenience", "parking", "utilities"],
};

export const EXCLUDED_AMENITIES: Record<string, string[]> = {
  land: [
    "Air Conditioning",
    "Furnished",
    "Partially Furnished",
    "Kitchen Appliances",
    "Washer",
    "Dryer",
    "Water Heater",
    "Balcony",
    "Storage Room",
    "Swimming Pool",
    "Kids Pool",
    "Playground",
    "Games Room",
    "Library",
    "Sky Lounge",
    "Rooftop Garden",
    "Cinema Room",
    "Elevator",
    "Lobby",
    "Mail Room",
    "Laundry Room",
    "Meeting Room",
    "Co-Working Space",
    "Fitness Center",
    "Yoga Room",
    "Spa",
    "Sauna",
    "Steam Room",
    "Massage Room",
    "Garden",
    "BBQ Area",
    "Tennis Court",
    "Basketball Court",
    "Jogging Track",
    "Mini Golf",
    "Lake View",
    "Sea View",
    "City View",
  ],
  commercial: [
    "Furnished",
    "Partially Furnished",
    "Kitchen Appliances",
    "Washer",
    "Dryer",
    "Swimming Pool",
    "Kids Pool",
    "Playground",
    "Games Room",
    "Library",
    "Sky Lounge",
    "Rooftop Garden",
    "Cinema Room",
    "Balcony",
    "Fitness Center",
    "Yoga Room",
    "Spa",
    "Sauna",
    "Steam Room",
    "Massage Room",
    "Tennis Court",
    "Basketball Court",
    "Jogging Track",
    "Mini Golf",
  ],
};
